AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
  TemplateVPC:
    Type: String
    Default: ./child_stack_template/vpc.yml # todo upload s3
  TemplateSG:
    Type: String
    Default: ./child_stack_template/sec.yml # todo upload s3
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateVPC
  SecurityGp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateSG
      Parameters: 
        VPCId: !ImportValue CreateVpc
    DependsOn: VPC
Outputs:
  VPCId:
    Value: !GetAtt VPC.Outputs.VPCId
    Description: VPC CIDR Block
  SSHHTTPSG:
    Value: !GetAtt SecurityGp.Outputs.SGSsHttp
    Description: SecurityGp for ssh and httph
