AWSTemplateFormatVersion: "2010-09-09"
#  _____                 _     _____  _                 _
# |  __ \               | |   / ____|| |               | |
# | |__) |  ___    ___  | |_ | (___  | |_   __ _   ___ | | __
# |  _  /  / _ \  / _ \ | __| \___ \ | __| / _` | / __|| |/ /
# | | \ \ | (_) || (_) || |_  ____) || |_ | (_| || (__ |   <
# |_|  \_\ \___/  \___/  \__||_____/  \__| \__,_| \___||_|\_\
Parameters: 
  TemplateVPC:
    Type: String
  TemplateInternetGateway:
    Type: String
  TemplateSubnetRoute:
    Type: String
  TemplateSecurityGroup:
    Type: String
  TemplateEC2:
    Type: String
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateVPC
  InternetGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateInternetGateway
    DependsOn: VPC
  SubnetRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateSubnetRoute
    DependsOn: InternetGateway
  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateSecurityGroup
    DependsOn: SubnetRoute
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateEC2
    DependsOn: SecurityGroup
