AWSTemplateFormatVersion: 2010-09-09
#  _____                 _
# |  __ \               | |
# | |__) |  ___   _   _ | |_   ___  _ __
# |  _  /  / _ \ | | | || __| / _ \| '__|
# | | \ \ | (_) || |_| || |_ |  __/| |
# |_|  \_\ \___/  \__,_| \__| \___||_|
Resources:
  Router:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue CreateVpc
      Tags:
      - Key: Name
        Value: cfn-training-router
  InternetGWAttacher:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !ImportValue CreateVpc
      InternetGatewayId: !ImportValue CreateIgw
  InternetGWRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGWAttacher
    Properties:
      RouteTableId: !Ref Router
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !ImportValue CreateIgw
Outputs:
  RouterOut:
    Value: !Ref Router
    Export:
      Name: CreateRouter
  IgwAtcOut:
    Value: !Ref InternetGWAttacher
    Export:
      Name: CreateIgwAtc
  IgwRouteOut:
    Value: !Ref InternetGWRoute
    Export:
      Name: CreateIgwRoute
