AWSTemplateFormatVersion: 2010-09-09
# | __|  __|_  )
# | _|  (     /   Amazon Linux 2 AMI
# |___|\___|___|
Parameters:
  EC2InstanceType:
    Type: String
    Default: t2.nano
  EC2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH public key
    Default: cfn-training
Resources:
  EC2Instance1a:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-097473abce069b8e9
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref EC2KeyName
      SubnetId: !ImportValue CreatePublicSubnet1a
      SecurityGroupIds: 
        - !ImportValue CreateSecGp
Outputs:
  Region:
    Description: Output Region
    Value: !Ref AWS::Region
